#!/usr/bin/env python
"""Program-A 3-arm config generator/template (pre-reg v3-A A4; critic condition 6).

CODE ONLY. Emits the three Program-A arm configs, parameterized by the calibrated
R2 L1 eps. All three are IDENTICAL except (a) allocation policy and (b) L1 eps;
they inherit the locked RAMP80 / APGD 10-10-10 / train49k-val1k base, so linf
(8/255) and L2 (0.5) threat models, epochs, batch size, optimizer, and eval grade
are shared verbatim.

  B4-adaptive              predictive_refresh (alpha 0.9, refresh 10, floor 30,
                           rule loss_plus_bind, cheap_probe false)
  B3-mis                   static_cycle [linf,linf,l2,l1] + static_extra linf /5
                           (aggregate_loss, 0.5/0.5)
  B3-bottleneck-informed   static_cycle [l1,l1,l2,linf] + static_extra l1 /5
                           (aggregate_loss, 0.5/0.5)

save_freq is set to 10 so ep020/ep040/ep060/ep080 checkpoints are written
(ep080/last/val_best are covered by the existing save logic; see
groupdro.save_checkpoint -> f"ep{epoch+1:03d}").

The generator does NOT choose the eps (that is the locked calibration, done later
on the `cal` split); it takes eps as a parameter. It refuses to overwrite an
existing file unless --force (fail-closed).
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys

import yaml

BASE = "configs/paper/reactive_softT_full10_ramp80_apgd_8255_t49k_v1k.yaml"

# (key, run-tag, allocation train-block) for each arm. train blocks carry ONLY
# the allocation policy + save_freq; everything else is inherited from BASE.
ARMS = {
    "b4_adaptive": {
        "variant_tags": ["family-predictive-allocation", "variant-programA-b4-adaptive"],
        "train": {
            "allocation_mode": "predictive_refresh",
            "predictive_refresh_every_n_batches": 10,
            "predictive_starvation_floor_batches": 30,
            "predictive_ema_alpha": 0.9,
            "predictive_use_cheap_probe": False,
            "predictive_score_rule": "loss_plus_bind",
            "predictive_log_batch_trace": True,
            "save_freq": 10,
        },
    },
    "b3_mis": {
        "variant_tags": ["family-static-allocation", "variant-programA-b3-mis"],
        "train": {
            "allocation_mode": "static_cycle",
            "static_cycle_order": ["linf", "linf", "l2", "l1"],
            "static_extra_source": "linf",
            "static_extra_every_n_batches": 5,
            "static_extra_mode": "aggregate_loss",
            "static_extra_primary_weight": 0.5,
            "static_extra_source_weight": 0.5,
            "save_freq": 10,
        },
    },
    "b3_bottleneck_informed": {
        "variant_tags": ["family-static-allocation", "variant-programA-b3-informed"],
        "train": {
            "allocation_mode": "static_cycle",
            "static_cycle_order": ["l1", "l1", "l2", "linf"],
            "static_extra_source": "l1",
            "static_extra_every_n_batches": 5,
            "static_extra_mode": "aggregate_loss",
            "static_extra_primary_weight": 0.5,
            "static_extra_source_weight": 0.5,
            "save_freq": 10,
        },
    },
}


def _sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _eps_tag(eps: float) -> str:
    return f"{eps:g}".replace(".", "p")


def build_arm_config(arm: str, eps: float) -> tuple[str, dict]:
    spec = ARMS[arm]
    eps_tag = _eps_tag(eps)
    run_name = f"programA_{arm}_l1eps{eps_tag}_ramp80_apgd_8255_t49k_v1k_s0"
    body = {
        "_base_": BASE,
        "run_name": run_name,
        # Only L1 eps is shifted for R2; linf 8/255 & L2 0.5 inherited unchanged.
        "threat_model": {"l1": {"eps": float(eps)}},
        "wandb": {
            "tags": [
                "cifar10", "prn18", "ramp80", "eps8255",
                "apgd-train-10-10-10", "eval-20-20-100", "t49k-v1k", "seed0",
                "programA", f"l1eps-{eps_tag}", *spec["variant_tags"],
            ],
            "tier": "in-house",
        },
        "train": dict(spec["train"]),
    }
    return run_name, body


def _header(arm: str, eps: float) -> str:
    return (
        f"# Program-A arm '{arm}' (pre-reg v3-A). GENERATED by "
        f"scripts/dev/gen_program_a_configs.py — do not hand-edit.\n"
        f"# Inherits {BASE}; differs from the other arms ONLY in allocation policy\n"
        f"# and L1 eps (= {float(eps)}). linf 8/255 & L2 0.5 unchanged. save_freq=10\n"
        f"# writes ep020/040/060/080. NOT launch-authorized until critic G2 Pass.\n"
    )


def write_configs(eps: float, out_dir: str, force: bool = False) -> list[tuple[str, str]]:
    os.makedirs(out_dir, exist_ok=True)
    eps_tag = _eps_tag(eps)
    out = []
    for arm in ARMS:
        run_name, body = build_arm_config(arm, eps)
        fname = f"programA_{arm}_l1eps{eps_tag}_ramp80_apgd_8255_t49k_v1k.yaml"
        path = os.path.join(out_dir, fname)
        if os.path.exists(path) and not force:
            raise FileExistsError(f"Refusing to overwrite {path!r} (use --force).")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_header(arm, eps))
            yaml.safe_dump(body, f, sort_keys=False, default_flow_style=False)
        out.append((path, _sha256_file(path)))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate the 3 Program-A arm configs.")
    ap.add_argument("--l1-eps", type=float, required=True,
                    help="Calibrated R2 L1 eps (from the locked cal-split calibration).")
    ap.add_argument("--out-dir", default="configs/paper",
                    help="Output dir (default: configs/paper).")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    written = write_configs(args.l1_eps, args.out_dir, force=args.force)
    print(f"=== Program-A configs (L1 eps={args.l1_eps:g}) ===")
    for path, sha in written:
        print(f"{path}\n  sha256: {sha}")


if __name__ == "__main__":
    main()
