#!/usr/bin/env python
"""Growing 3-seed table for the reactive-vs-predictive @8/255 pair.

Scans whatever seed eval JSONs exist and (re)writes
results/reports/reactive_vs_predictive_3seed.md with per-seed unions + mean±std +
per-norm means + measured attack-FLOPs, all vs RAMP repro 46.1. Idempotent —
the chain re-runs it after every seed pair lands, so the file always reflects
current reality even if later seeds are mid-run.
"""
from __future__ import annotations
import json
import os

ROOT = "/mnt/c/Users/ADMIN/Documents/Claude/Projects/ATTACKDRO"
SEEDS = (0, 1, 2)
RAMP_JSON = "results/eval_ramp_repro_eps8255_apgd_n1000.json"


def _load(path):
    p = os.path.join(ROOT, path)
    if not os.path.exists(p):
        return None
    with open(p) as f:
        return json.load(f)


def _union(evj):
    if not evj:
        return None
    m = evj.get("metrics", evj)
    return m.get("worst_union_acc")


def _pernorm(evj):
    if not evj:
        return {}
    return (evj.get("metrics", evj).get("per_norm_robust_acc", {}) or {})


def _flops(seed):
    tj = _load(f"results/predictive_pb_8255_s{seed}.json")
    if not tj:
        return None
    post = [h["efficiency/attack_flops_ratio"] for h in tj.get("history", [])
            if h.get("epoch", 0) >= 5 and "efficiency/attack_flops_ratio" in h]
    if not post:
        post = [h["pb/attack_flops_ratio"] for h in tj.get("history", [])
                if h.get("epoch", 0) >= 5 and "pb/attack_flops_ratio" in h]
    return (sum(post) / len(post)) if post else None


def _stats(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None, 0
    mean = sum(vals) / len(vals)
    if len(vals) < 2:
        return mean, 0.0, len(vals)
    var = sum((v - mean) ** 2 for v in vals) / (len(vals) - 1)
    return mean, var ** 0.5, len(vals)


def _cell(mean, std, n):
    if mean is None:
        return "—"
    if n < 2:
        return f"{100*mean:.1f} (s0)"
    return f"{100*mean:.1f}±{100*std:.2f} (n={n})"


def main():
    react = {s: _load(f"results/eval_reactive_T025_8255_s{s}.json") for s in SEEDS}
    pred = {s: _load(f"results/eval_predictive_pb_8255_s{s}.json") for s in SEEDS}
    ramp_u = _union(_load(RAMP_JSON)) or 0.461

    ru = _stats([_union(react[s]) for s in SEEDS])
    pu = _stats([_union(pred[s]) for s in SEEDS])
    fl = _stats([_flops(s) for s in SEEDS])
    rnorm = {n: _stats([_pernorm(react[s]).get(n) for s in SEEDS]) for n in ("linf", "l2", "l1")}
    pnorm = {n: _stats([_pernorm(pred[s]).get(n) for s in SEEDS]) for n in ("linf", "l2", "l1")}

    L = []
    L.append("# Reactive vs Predictive @8/255 — 3-seed running table")
    L.append("")
    L.append("Regenerated by `scripts/dev/pair_table.py` after each seed pair lands "
             "(train==eval@8/255, APGD n=1000). Cells show mean±std once ≥2 seeds are in. "
             "The s0 go/no-go verdict lives in `reactive_vs_predictive_s0.md`.")
    L.append("")
    L.append("| method | union | linf | l2 | l1 | attack-FLOPs |")
    L.append("|---|---|---|---|---|---|")
    L.append(f"| reactive (soft T=0.25) | **{_cell(*ru)}** | {_cell(*rnorm['linf'])} "
             f"| {_cell(*rnorm['l2'])} | {_cell(*rnorm['l1'])} | 1.00 |")
    L.append(f"| predictive (CARD-PB) | **{_cell(*pu)}** | {_cell(*pnorm['linf'])} "
             f"| {_cell(*pnorm['l2'])} | {_cell(*pnorm['l1'])} | {_cell(*fl)} |")
    L.append(f"| RAMP repro (matched) | {100*ramp_u:.1f} | — | — | — | 1.00 |")
    L.append("")
    if ru[0] is not None and pu[0] is not None:
        L.append(f"- **Δunion (predictive − reactive) = {100*(pu[0]-ru[0]):+.2f} pp** "
                 f"(reactive n={ru[2]}, predictive n={pu[2]}).")
        if fl[0] is not None:
            L.append(f"- **Measured attack-FLOPs = {fl[0]:.3f}×** (mean over "
                     f"predictive seeds, post-cold).")
        L.append(f"- vs RAMP 46.1: reactive {100*(ru[0]-ramp_u):+.2f} pp, "
                 f"predictive {100*(pu[0]-ramp_u):+.2f} pp.")
    L.append("")
    L.append("_Per-seed unions:_ "
             + "reactive " + ", ".join(f"s{s}={_fmt(_union(react[s]))}" for s in SEEDS)
             + " · predictive " + ", ".join(f"s{s}={_fmt(_union(pred[s]))}" for s in SEEDS))

    out = os.path.join(ROOT, "results/reports/reactive_vs_predictive_3seed.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"[pair_table] wrote {out} (reactive n={ru[2]}, predictive n={pu[2]})")


def _fmt(u):
    return f"{100*u:.1f}" if u is not None else "—"


if __name__ == "__main__":
    main()
