#!/usr/bin/env bash
# =============================================================================
# P1 unattended pipeline — self-contained, runs in tmux, survives disconnect.
#
# Order (GPU-friendly: waits for pgdat to finish first so nothing contends):
#   1. Wait for the pgdat training run to finish.
#   2. Baseline table: eval all 6 locuslab checkpoints (n=1000, apgd).
#   3. Eval our pgdat best checkpoint (reference point).
#   4. For seed in 0 1 2: train AttackDRO++ (50 ep) -> eval_union (n=1000, apgd).
#   5. After EACH seed, append numbers to results/p1_summary.md (incremental).
#
# Everything logs to logs/. Robust to individual step failure (|| true).
# Launch with:  tmux new-session -d -s p1pipe 'bash scripts/run_p1_pipeline.sh'
# =============================================================================
set -uo pipefail
cd /mnt/c/Users/ADMIN/Documents/Claude/Projects/ATTACKDRO
PY=/mnt/c/Users/ADMIN/Documents/Claude/Projects/ATTACKDRO/.venv/bin/python
mkdir -p logs results
SUMMARY=results/p1_summary.md
SEEDS=(0 1 2)

log() { echo "[p1pipe $(date +%H:%M:%S)] $*"; }

log "pipeline start"

# --- 1. Wait for pgdat to finish (skip if it already produced its results) --
if [ -f results/pgd_at_linf.json ] && [ -f checkpoints/pgd_at_linf_best.pt ]; then
  log "pgdat already finished (results + checkpoint present) -> not waiting"
else
  log "waiting for pgdat training to finish..."
  # Match the actual python process (not the tmux/bash wrapper command string).
  while pgrep -f "[.]venv/bin/python -u scripts/train.py --config configs/pgd_at" >/dev/null; do sleep 30; done
  log "pgdat finished."
fi

# Kill any stray baseline-eval left over from the interactive session so it
# doesn't contend with this pipeline.
pkill -f eval_baselines.py 2>/dev/null || true
sleep 3

# --- 2. Baseline table (n=1000) — skip if already computed -----------------
if grep -q "n=1000" results/baseline_table.md 2>/dev/null; then
  log "STEP 1: baseline table already exists (n=1000) -> skipping"
else
  log "STEP 1: baseline table (n=1000, apgd)"
  $PY scripts/eval_baselines.py -n 1000 --version apgd --bs 500 > logs/baseline_table.log 2>&1 || true
fi
log "baseline table ready -> results/baseline_table.md"

# --- 3. Eval our pgdat best checkpoint -------------------------------------
log "STEP 2: eval pgdat best checkpoint (n=1000, apgd)"
$PY scripts/evaluate.py --config configs/pgd_at.yaml \
    --checkpoint checkpoints/pgd_at_linf_best.pt -n 1000 --version apgd \
    > logs/eval_pgdat.log 2>&1 || true
log "pgdat eval done -> results/eval_pgd_at_linf_best.json"

# --- init summary ----------------------------------------------------------
{
  echo "# P1 summary (auto-generated by run_p1_pipeline.sh)"
  echo ""
  echo "Locked protocol: eps_inf=0.03, l2=0.5, l1=12; n=1000; AutoAttack apgd (CE+T)."
  echo ""
  echo "## Baselines"
  cat results/baseline_table.md 2>/dev/null | grep '^|' || echo "(baseline table missing)"
  echo ""
  echo "## AttackDRO++ (this pipeline)"
  echo "| seed | clean | l_inf | l2 | l1 | worst-union |"
  echo "|---|---|---|---|---|---|"
} > "$SUMMARY"

# --- 4/5. Train AttackDRO++ per seed, eval, append -------------------------
for S in "${SEEDS[@]}"; do
  RUN="attackdro_union_s${S}"
  log "STEP 3 seed=$S: training $RUN (50 epochs)"
  $PY scripts/train.py --config configs/attackdro.yaml \
      --seed "$S" --run-name "$RUN" > "logs/${RUN}.log" 2>&1 || { log "train seed $S FAILED"; continue; }
  log "seed=$S training done; eval_union"

  CKPT="checkpoints/${RUN}_best.pt"
  $PY scripts/evaluate.py --config configs/attackdro.yaml \
      --checkpoint "$CKPT" -n 1000 --version apgd \
      --out "results/eval_${RUN}.json" > "logs/eval_${RUN}.log" 2>&1 || { log "eval seed $S FAILED"; continue; }

  # Pull the five numbers out of the eval JSON and append a summary row.
  $PY - "$S" "results/eval_${RUN}.json" "$SUMMARY" <<'PYEOF'
import json, sys
seed, path, summ = sys.argv[1], sys.argv[2], sys.argv[3]
m = json.load(open(path))["metrics"]
row = (f"| {seed} | {m['clean_acc']*100:.1f} | "
       f"{m['per_norm_robust_acc']['linf']*100:.1f} | "
       f"{m['per_norm_robust_acc']['l2']*100:.1f} | "
       f"{m['per_norm_robust_acc']['l1']*100:.1f} | "
       f"{m['worst_union_acc']*100:.1f} |")
open(summ, "a").write(row + "\n")
print("appended:", row)
PYEOF
  log "seed=$S appended to $SUMMARY"
done

# --- 6. Auto-analysis: verdict + append to PROGRESS.md ----------------------
log "STEP 3 analysis: writing GO/NO-GO to PROGRESS.md + $SUMMARY"
$PY - <<'PYEOF'
import glob, json, os, statistics

def pct(v):
    return v * 100.0

# Baseline MSD union (baseline_table.json stores percentages already).
msd = None
try:
    bt = json.load(open("results/baseline_table.json"))["rows"]
    msd = bt.get("MSD", {}).get("union")
except Exception as e:
    print("could not read baseline table:", e)

# pgdat reference (eval json stores fractions under metrics).
pgdat = None
try:
    pm = json.load(open("results/eval_pgd_at_linf_best.json"))["metrics"]
    pgdat = {"clean": pct(pm["clean_acc"]),
             "linf": pct(pm["per_norm_robust_acc"]["linf"]),
             "l2": pct(pm["per_norm_robust_acc"]["l2"]),
             "l1": pct(pm["per_norm_robust_acc"]["l1"]),
             "union": pct(pm["worst_union_acc"])}
except Exception as e:
    print("could not read pgdat eval:", e)

# AttackDRO++ seeds.
seeds = []
for path in sorted(glob.glob("results/eval_attackdro_union_s*.json")):
    try:
        m = json.load(open(path))["metrics"]
        seeds.append({"path": path,
                      "clean": pct(m["clean_acc"]),
                      "linf": pct(m["per_norm_robust_acc"]["linf"]),
                      "l2": pct(m["per_norm_robust_acc"]["l2"]),
                      "l1": pct(m["per_norm_robust_acc"]["l1"]),
                      "union": pct(m["worst_union_acc"])})
    except Exception as e:
        print("skip", path, e)

lines = []
lines.append("\n## 2026-07-01 — P1 RESULTS (auto-generated by run_p1_pipeline.sh)\n")
lines.append(f"Locked protocol: eps_inf=0.03, l2=0.5, l1=12; n=1000; AutoAttack apgd (CE+T).\n")
lines.append("| model | clean | l_inf | l2 | l1 | worst-union |")
lines.append("|---|---|---|---|---|---|")
if msd is not None:
    bt = json.load(open("results/baseline_table.json"))["rows"]["MSD"]
    lines.append(f"| MSD (baseline, best union) | {bt['clean']:.1f} | {bt['linf']:.1f} | {bt['l2']:.1f} | {bt['l1']:.1f} | **{bt['union']:.1f}** |")
if pgdat is not None:
    lines.append(f"| pgdat (l_inf-AT, 8/255 recipe) | {pgdat['clean']:.1f} | {pgdat['linf']:.1f} | {pgdat['l2']:.1f} | {pgdat['l1']:.1f} | {pgdat['union']:.1f} |")
for i, s in enumerate(seeds):
    lines.append(f"| AttackDRO++ seed{i} | {s['clean']:.1f} | {s['linf']:.1f} | {s['l2']:.1f} | {s['l1']:.1f} | **{s['union']:.1f}** |")

verdict = "INCONCLUSIVE (no AttackDRO++ evals found)"
if seeds and msd is not None:
    unions = [s["union"] for s in seeds]
    best = max(unions)
    mean = statistics.mean(unions)
    std = statistics.pstdev(unions) if len(unions) > 1 else 0.0
    lines.append("")
    lines.append(f"AttackDRO++ worst-union: best={best:.1f}, mean={mean:.1f} ± {std:.1f} (n={len(unions)} seeds).")
    lines.append(f"MSD baseline worst-union: {msd:.1f}.")
    delta = best - msd
    if delta > 1.0:
        verdict = (f"**GO (provisional)** — best AttackDRO++ union {best:.1f} > MSD {msd:.1f} "
                   f"(+{delta:.1f}). PROVISIONAL: baselines use locuslab's training recipe while "
                   f"AttackDRO++ uses ours — retrain AVG/MAX in-house under our recipe before any claim.")
    elif delta > -1.0:
        verdict = (f"**NO-GO / TIE** — best AttackDRO++ union {best:.1f} ≈ MSD {msd:.1f} "
                   f"({delta:+.1f}, within noise). Difficulty-aware DRO did not move worst-case union. "
                   f"This is the EXPECTED result (thesis improved average-case, not worst-case) → trigger P2.")
    else:
        verdict = (f"**NO-GO** — best AttackDRO++ union {best:.1f} < MSD {msd:.1f} ({delta:+.1f}). "
                   f"Difficulty-aware DRO over the union did not beat MSD on worst-case. "
                   f"EXPECTED, informative negative result → trigger P2 (grouping signal / objective / l1 / mechanism).")
lines.append("")
lines.append(f"**VERDICT: {verdict}**")
lines.append("")
lines.append("_Note: numbers are AutoAttack `apgd` (CE+T). Re-run the winner + baselines with "
             "`--version standard` (full AutoAttack) for final paper numbers. Analysis written "
             "automatically; a human-reviewed writeup follows._")

block = "\n".join(lines) + "\n"
with open("PROGRESS.md", "a") as f:
    f.write(block)
with open("results/p1_summary.md", "a") as f:
    f.write(block)
print("wrote verdict:\n", verdict)
PYEOF

log "PIPELINE COMPLETE. Verdict appended to PROGRESS.md + $SUMMARY"
