#!/usr/bin/env bash
# =============================================================================
# P2 pipeline — CARD-3a (bindaware) pilot FIRST, then CARD-1 (avg_frozen).
# Self-contained, runs in tmux, survives disconnect. Runs concurrently with
# p1pipe (VRAM is abundant); avg_frozen waits for p1's attackdro runs to finish
# so it doesn't slow the priority CARD-3a pilot.
#
#   1. CARD-3a bindaware seed 0 pilot -> eval_union (n=1000, apgd).   [priority]
#   2. wait for p1pipe's attackdro runs to finish (free the GPU).
#   3. CARD-1 avg_frozen seeds 0,1,2 -> eval_union each.             [final table]
# Each run's numbers appended to results/p2_summary.md.
# =============================================================================
set -uo pipefail
cd /mnt/c/Users/ADMIN/Documents/Claude/Projects/ATTACKDRO
PY=/mnt/c/Users/ADMIN/Documents/Claude/Projects/ATTACKDRO/.venv/bin/python
mkdir -p logs results
SUMM=results/p2_summary.md
log() { echo "[p2pipe $(date +%H:%M:%S)] $*"; }

run_and_eval() {  # $1=config-name  $2=run-name  $3=seed
  local cfg=$1 run=$2 seed=$3
  log "TRAIN $run (config=$cfg, seed=$seed)"
  $PY scripts/train.py --config "configs/${cfg}.yaml" --seed "$seed" --run-name "$run" \
      > "logs/${run}.log" 2>&1 || { log "$run TRAIN FAILED"; return 1; }
  log "EVAL $run (n=1000, apgd)"
  $PY scripts/evaluate.py --config "configs/${cfg}.yaml" \
      --checkpoint "checkpoints/${run}_best.pt" -n 1000 --version apgd \
      --out "results/eval_${run}.json" > "logs/eval_${run}.log" 2>&1 || { log "$run EVAL FAILED"; return 1; }
  $PY - "$run" "results/eval_${run}.json" "$SUMM" <<'PYEOF'
import json, sys
run, path, summ = sys.argv[1], sys.argv[2], sys.argv[3]
m = json.load(open(path))["metrics"]
row = (f"| {run} | {m['clean_acc']*100:.1f} | {m['per_norm_robust_acc']['linf']*100:.1f} | "
       f"{m['per_norm_robust_acc']['l2']*100:.1f} | {m['per_norm_robust_acc']['l1']*100:.1f} | "
       f"**{m['worst_union_acc']*100:.1f}** |")
open(summ, "a").write(row + "\n"); print("appended:", row)
PYEOF
  log "$run -> appended to $SUMM"
}

if [ ! -f "$SUMM" ]; then
  { echo "# P2 summary (auto-generated by run_p2_pipeline.sh)";
    echo ""; echo "Locked protocol: eps_inf=0.03, l2=0.5, l1=12; n=1000; AutoAttack apgd (CE+T).";
    echo "Baselines (ref): MSD 42.5 · AVG 38.7 · MAX 25.0. AttackDRO++ P1 seed0: 38.7.";
    echo ""; echo "| run | clean | l_inf | l2 | l1 | worst-union |"; echo "|---|---|---|---|---|---|"; } > "$SUMM"
fi

# --- 1. CARD-3a bindaware pilot (priority; concurrent with p1pipe) ----------
run_and_eval bindaware bindaware_s0 0

# --- 2. wait for p1pipe's attackdro runs to free the GPU --------------------
log "CARD-3a pilot done. Waiting for p1pipe (attackdro seeds) to finish before avg_frozen..."
while pgrep -f "[.]venv/bin/python .*scripts/train.py --config configs/attackdro.yaml" >/dev/null; do sleep 60; done
log "p1 attackdro runs finished."

# --- 3. CARD-1 avg_frozen 3 seeds (in-house AVG for final table) ------------
for S in 0 1 2; do run_and_eval avg_frozen "avg_frozen_s${S}" "$S"; done

log "P2PIPE COMPLETE (CARD-3a pilot + CARD-1 avg_frozen). See $SUMM"
