#!/usr/bin/env python
"""s0 WAKE-UP decision artifact for the reactive-vs-predictive paper chain.

Reads the seed-0 eval JSONs (reactive + predictive) and the predictive TRAINING
history (for the MEASURED attack-FLOPs ratio / floor / phi), compares against the
matched RAMP repro (union @8/255), writes results/reactive_vs_predictive_s0.md,
and prints a machine-readable `DECISION=CONTINUE_BOTH|KILL_PREDICTIVE` line the
chain script greps to branch the gated continuation.

Pre-registration (Kiet, 2026-07-06):
  * noise band ~ +/-0.3pp on union.
  * efficiency signal = |Δunion| within noise AND measured FLOPs <= 0.60.
  * CLEARLY NEGATIVE (=> STOP predictive, continue reactive only) iff
      Δunion < -noise  OR  any norm dropped > 2pp vs reactive (final eval =
      post-floor-recovery state; a norm still >2pp down means the floor did not
      recover it).
  * Missing/failed predictive data => KILL_PREDICTIVE (don't burn GPU on an
      unvalidated method; reactive baseline is needed regardless).
"""
from __future__ import annotations
import json
import os
import sys

ROOT = "/mnt/c/Users/ADMIN/Documents/Claude/Projects/ATTACKDRO"
NOISE = 0.3          # pp, union noise band
NORM_DROP = 2.0      # pp, per-norm collapse threshold
FLOPS_TARGET = 0.60  # measured attack-FLOPs ceiling for the efficiency claim
COLD = 5             # predictive cold-start epochs (exclude from FLOPs mean)
RAMP_JSON = "results/eval_ramp_repro_eps8255_apgd_n1000.json"


def _load(path):
    p = os.path.join(ROOT, path)
    if not os.path.exists(p):
        return None
    with open(p) as f:
        return json.load(f)


def _metrics(evj):
    """eval JSON -> flat dict of fractions, or None."""
    if not evj:
        return None
    m = evj.get("metrics", evj)
    if m.get("worst_union_acc") is None:
        return None
    pn = m.get("per_norm_robust_acc", {}) or {}
    return {
        "union": m["worst_union_acc"],
        "clean": m.get("clean_acc"),
        "avg": m.get("avg_robust_acc"),
        "linf": pn.get("linf"), "l2": pn.get("l2"), "l1": pn.get("l1"),
    }


def _pred_train_stats(trainj):
    """predictive training history -> measured FLOPs ratio (post-cold mean),
    final floor per norm, final phi misprediction rate."""
    if not trainj:
        return {}
    hist = trainj.get("history", []) or []
    post = [h for h in hist if h.get("epoch", 0) >= COLD]
    flops = [h["pb/attack_flops_ratio"] for h in post if "pb/attack_flops_ratio" in h]
    last = hist[-1] if hist else {}
    return {
        "flops_ratio": (sum(flops) / len(flops)) if flops else None,
        "floor": {n: last.get(f"floor/{n}") for n in ("linf", "l2", "l1")},
        "phi_mispred": last.get("phi/misprediction_rate"),
        "beta": last.get("pb/beta"),
    }


def _pct(x):
    return f"{100 * x:.1f}" if isinstance(x, (int, float)) else "—"


def main():
    react = _metrics(_load("results/eval_reactive_T025_8255_s0.json"))
    pred = _metrics(_load("results/eval_predictive_pb_8255_s0.json"))
    ramp = _metrics(_load(RAMP_JSON))
    pstats = _pred_train_stats(_load("results/predictive_pb_8255_s0.json"))
    ramp_u = ramp["union"] if ramp else 0.461

    lines = []
    lines.append("# Reactive vs Predictive @8/255 — seed-0 WAKE-UP decision")
    lines.append("")
    lines.append("Auto-generated by `scripts/dev/s0_decision.py` the moment the s0 pair "
                 "finished eval (APGD, n=1000, train==eval@8/255). Later seeds may still "
                 "be mid-run; this is the s0 read for the go/no-go on the paper claim.")
    lines.append("")

    if not react or not pred:
        # Can't validate the method — conservative branch.
        decision = "KILL_PREDICTIVE"
        lines.append("## ⚠ INCOMPLETE — predictive or reactive s0 eval missing")
        lines.append("")
        lines.append(f"- reactive eval present: **{bool(react)}**")
        lines.append(f"- predictive eval present: **{bool(pred)}**")
        lines.append("")
        lines.append("**Decision: KILL_PREDICTIVE** (unvalidated → don't burn ~6h of GPU "
                     "on the predictive seeds; reactive s1/s2 continue as the needed baseline). "
                     "Re-run predictive manually once the failure is understood.")
        _write(lines)
        print(f"DECISION={decision}")
        return

    du = 100 * (pred["union"] - react["union"])           # Δunion, pp
    norm_deltas = {n: 100 * (pred[n] - react[n]) for n in ("linf", "l2", "l1")
                   if pred.get(n) is not None and react.get(n) is not None}
    min_norm = min(norm_deltas.values()) if norm_deltas else 0.0
    worst_norm = min(norm_deltas, key=norm_deltas.get) if norm_deltas else "—"
    flops = pstats.get("flops_ratio")

    negative = (du < -NOISE) or (min_norm < -NORM_DROP)
    decision = "KILL_PREDICTIVE" if negative else "CONTINUE_BOTH"
    eff_signal = (abs(du) <= NOISE) and (flops is not None and flops <= FLOPS_TARGET)

    lines.append("## Headline (seed-0)")
    lines.append("")
    lines.append("| method | union | clean | linf | l2 | l1 | attack-FLOPs |")
    lines.append("|---|---|---|---|---|---|---|")
    lines.append(f"| reactive (soft T=0.25) | **{_pct(react['union'])}** | {_pct(react['clean'])} "
                 f"| {_pct(react['linf'])} | {_pct(react['l2'])} | {_pct(react['l1'])} | 1.00 (ref) |")
    lines.append(f"| predictive (CARD-PB) | **{_pct(pred['union'])}** | {_pct(pred['clean'])} "
                 f"| {_pct(pred['linf'])} | {_pct(pred['l2'])} | {_pct(pred['l1'])} | "
                 f"{flops:.3f} |" if flops is not None else
                 f"| predictive (CARD-PB) | **{_pct(pred['union'])}** | {_pct(pred['clean'])} "
                 f"| {_pct(pred['linf'])} | {_pct(pred['l2'])} | {_pct(pred['l1'])} | — |")
    lines.append(f"| RAMP repro (matched) | {_pct(ramp_u)} | — | — | — | — | 1.00 |")
    lines.append("")
    lines.append(f"- **Δunion (predictive − reactive) = {du:+.2f} pp** (noise band ±{NOISE}).")
    lines.append(f"- **Worst per-norm move: {worst_norm} {min_norm:+.2f} pp** "
                 f"(collapse threshold −{NORM_DROP}).")
    if flops is not None:
        lines.append(f"- **Measured attack-FLOPs ratio (post-cold mean) = {flops:.3f}** "
                     f"(target ≤ {FLOPS_TARGET}). φ misprediction (final) = "
                     f"{pstats.get('phi_mispred')}. Final floor = {pstats.get('floor')} "
                     f"(base 3 → any >3 = adaptive raise fired). β = {pstats.get('beta')}.")
    lines.append(f"- vs RAMP: reactive {100*(react['union']-ramp_u):+.2f} pp, "
                 f"predictive {100*(pred['union']-ramp_u):+.2f} pp.")
    lines.append("")

    lines.append("## Verdict")
    lines.append("")
    if negative:
        why = []
        if du < -NOISE:
            why.append(f"Δunion {du:+.2f} < −{NOISE}")
        if min_norm < -NORM_DROP:
            why.append(f"{worst_norm} dropped {min_norm:+.2f} pp (>−{NORM_DROP}, floor did not recover it)")
        lines.append(f"**CLEARLY NEGATIVE** ({'; '.join(why)}). → **STOP predictive**; "
                     "continue ONLY reactive s1, s2 (baseline needed regardless). Predictive "
                     "kill logged. Do NOT escalate.")
    elif eff_signal:
        lines.append(f"**EFFICIENCY SIGNAL** — union within noise (Δ {du:+.2f} pp) at "
                     f"{flops:.3f}× attack-FLOPs (≤{FLOPS_TARGET}). → continue reactive AND "
                     "predictive s1, s2 for the 3-seed pair. 20-seed escalation is **Kiet's call** "
                     "(do not launch unattended).")
    else:
        lines.append(f"**NOT NEGATIVE, efficiency not yet clean** (Δunion {du:+.2f} pp within "
                     f"noise but FLOPs={flops}). → continue reactive AND predictive s1, s2; "
                     "re-read efficiency on the 3-seed means.")
    lines.append("")
    lines.append(f"<!-- DECISION={decision} du={du:.3f} min_norm={min_norm:.3f} "
                 f"flops={flops} -->")
    _write(lines)
    print(f"DECISION={decision}")


def _write(lines):
    out = os.path.join(ROOT, "results/reactive_vs_predictive_s0.md")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[s0_decision] wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
